services:
  - type: web
    name: event-scheduler-app
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    rootDir: .
    envVars:
      - key: PORT
        value: 10000
